---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.kubefed.io
  resources:
  - kubefedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kubefed.io
  resources:
  - kubefedclusters/status
  verbs:
  - get
- apiGroups:
  - scheduling.kubefed.io
  resources:
  - replicaschedulingpreferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - types.kubefed.io
  resources:
  - federateddeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - waofedconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - waofedconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - waofedconfigs/status
  verbs:
  - get
  - patch
  - update
