---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - autorsps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - autorsps/finalizers
  verbs:
  - update
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - autorsps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - waofedconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - waofedconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - waofedconfigs/status
  verbs:
  - get
  - patch
  - update
