# permissions for end users to edit waofedconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: waofedconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: waofed
    app.kubernetes.io/part-of: waofed
    app.kubernetes.io/managed-by: kustomize
  name: waofedconfig-editor-role
rules:
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - waofedconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - waofed.bitmedia.co.jp
  resources:
  - waofedconfigs/status
  verbs:
  - get
